catalog
EgorRyazanov/sci-join pull request #12
Opened 2024-04-21 14:56 UTC by nchertolin

2024-04-25 19:13 UTC, EgorRyazanov requested changes

2024-04-25 19:13 UTC, EgorRyazanov commented on src/features/catalog/Search/api/types.ts
> +export type ScientificAreasModel = Array<{
Думаю, лучше создать тип  ScientificAreaModel, а там, где нужно уже подставлять Array

2024-04-25 19:13 UTC, EgorRyazanov commented on src/features/catalog/Search/lib/helpers/transformDataForAutocomplete.ts
> +    options.reduce((acc: ScientificAreasModel, current) => {
вместо reduce лучше map

2024-04-25 19:13 UTC, EgorRyazanov commented on src/features/catalog/Search/ui/CatalogSearch.tsx
> +    const [searchText] = useDebounce(search, 500);
Думаю, стоит вынести время 500 в константу, чтоб мы везде могли одинаковое использовать

2024-04-25 19:13 UTC, EgorRyazanov commented on src/features/catalog/Search/ui/CatalogSearch.tsx
> +    const [search, setSearch] = useState<string>('');
По моему мнению, можно вместо useState<string>(''), использовать useState(''). Он сам подхватит типы исходя из начального значения

2024-04-25 19:13 UTC, EgorRyazanov commented on src/shared/lib/types/catalogOptions.ts
>  export enum CatalogOptions {
CatalogOptions странно видеть в shared слое

2024-04-25 19:13 UTC, EgorRyazanov commented on src/shared/lib/types/userStatus.ts
> +    Active,
То же, что и сверху

2024-04-25 19:13 UTC, EgorRyazanov commented on src/shared/lib/types/workStatus.ts
> +export enum WorkStatus {
То же, что и сверху

2024-04-25 19:13 UTC, EgorRyazanov commented on src/shared/ui/LimitInfo/LimitInfo.tsx
> +    readonly fullness: number;
может, пересмотришь наминг. Total,вместо fullness

2024-04-25 19:13 UTC, EgorRyazanov commented on src/widgets/Catalog/api/catalogApi.ts
> +            query: ({ params, option }) => {
widget никак не должен взаимодействовать с api

2024-04-25 19:13 UTC, EgorRyazanov commented on src/widgets/Catalog/api/types.ts
> +export interface CatalogModel {
модельки нужно хранить в папке model

2024-04-25 19:13 UTC, EgorRyazanov commented on src/widgets/Catalog/api/catalogApi.ts
> +const catalogApi = baseApi.injectEndpoints({
думаю, лучше сделать три разных запроса, чем динамически определять URL. Потом на уровне view брать данные из разных мест по проверке по роли пользователя или другим признакам

2024-04-25 19:13 UTC, EgorRyazanov commented on src/widgets/Catalog/lib/helpers/getUrl.ts
> +    [CatalogOptions.Professors]: Urls.Professors,
в целом, прикольная идея хранить все урлы. Понимаю, что задумывалась для динамического определения, но давай эту штуку переделаем в статический класс, который будет хранить публиные объекты по областям (урлы авторизация, урлы каталога)

2024-04-25 19:13 UTC, EgorRyazanov commented on src/widgets/Catalog/ui/Catalog.tsx
> +    const { isFetching, data } = useGetCatalogQuery({ option, params: { page, pageSize } });
нужно как-то обрабатывать ошибки, показывать в toastify, например

2024-04-25 19:13 UTC, EgorRyazanov commented on src/widgets/Catalog/ui/Catalog.tsx
> +                        <CatalogList items={data?.data || []} />
еще хорошей практикой обработать ситуацию, если пришел пустой список. Допустим, "Ничего не найдено"

2024-04-25 19:13 UTC, EgorRyazanov commented on src/widgets/CatalogCard/ui/CatalogCard.skeleton.tsx
> +                        width={`${Math.floor(Math.random() * (40 - 20 + 1)) + 10}%`}
думаю, лучше задать всем статичное одинаковое значение

2024-04-26 18:22 UTC, nchertolin commented on src/shared/ui/LimitInfo/LimitInfo.tsx
> +    readonly fullness: number;
они на бэке так сделали, мне впадлу менять :)

2024-04-26 18:30 UTC, nchertolin commented on src/widgets/CatalogCard/ui/CatalogCard.skeleton.tsx
> +                        width={`${Math.floor(Math.random() * (40 - 20 + 1)) + 10}%`}
а оно так некрасиво смотрелось, я поэтому решил так сделать

2024-05-21 18:43 UTC, EgorRyazanov approved these changes

2024-05-21 18:43 UTC, EgorRyazanov commented on src/entities/CatalogCard/model/types/ICatalogCard.ts
> +export interface ICatalogCard {
просто CatalogCard, не нужно подставлять приставку I

2024-05-21 18:43 UTC, merged